# Generated by Django 4.0.6 on 2022-08-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahiaApp', '0002_inicio_rename_prueba_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='pag1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pag2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='about',
        ),
        migrations.DeleteModel(
            name='inicio',
        ),
    ]
