# Generated by Django 4.0.6 on 2022-08-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bahiaApp', '0003_pag1_pag2_delete_about_delete_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pag1',
            name='inicio',
        ),
    ]
