# Generated by Django 4.0.6 on 2022-08-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahiaApp', '0004_remove_pag1_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Formulario de contacto',
            },
        ),
        migrations.CreateModel(
            name='pag3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(default='', max_length=50)),
                ('descripcion', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='pag4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contactanos',
            },
        ),
        migrations.AlterModelOptions(
            name='pag1',
            options={'verbose_name_plural': 'Inicio'},
        ),
        migrations.AlterModelOptions(
            name='pag2',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.RenameField(
            model_name='pag1',
            old_name='content',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='pag1',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='pag2',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='pag2',
            name='content',
        ),
        migrations.AddField(
            model_name='pag1',
            name='testimonio1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pag1',
            name='testimonio2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pag1',
            name='testimonio3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pag2',
            name='barbi_1',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='pag2',
            name='barbi_2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pag2',
            name='barbi_3',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='pag2',
            name='contenido',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='pag2',
            name='tofi_1',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='pag2',
            name='tofi_2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='pag2',
            name='tofi_3',
            field=models.CharField(default='', max_length=80),
        ),
    ]
