# Generated by Django 4.0.6 on 2022-08-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahiaApp', '0005_formulario_pag3_pag4_alter_pag1_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pag1',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
