# Generated by Django 4.0.6 on 2022-08-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahiaApp', '0006_pag1_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pag1',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
