# Generated by Django 4.0.6 on 2022-08-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahiaApp', '0007_alter_pag1_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pag1',
            name='contenido',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pag1',
            name='testimonio1',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pag1',
            name='testimonio2',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pag1',
            name='testimonio3',
            field=models.TextField(default='', max_length=50),
        ),
    ]
