# Generated by Django 4.0.6 on 2022-08-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahiaApp', '0008_alter_pag1_contenido_alter_pag1_testimonio1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'verbose_name_plural': 'Respuestas de formulario'},
        ),
        migrations.AlterModelOptions(
            name='pag2',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='frase',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='formulario',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='formulario',
            name='mensaje',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='formulario',
            name='telefono',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='pag2',
            name='barbi_1',
            field=models.TextField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='pag2',
            name='barbi_2',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pag2',
            name='barbi_3',
            field=models.TextField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='pag2',
            name='contenido',
            field=models.TextField(default='a', max_length=400),
        ),
        migrations.AlterField(
            model_name='pag2',
            name='tofi_1',
            field=models.TextField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='pag2',
            name='tofi_2',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='pag2',
            name='tofi_3',
            field=models.TextField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='pag3',
            name='descripcion',
            field=models.TextField(default='', max_length=100),
        ),
    ]
