# Generated by Django 4.0.6 on 2022-08-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahiaApp', '0009_alter_formulario_options_alter_pag2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pag2',
            name='imagen_barbi',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='pag2',
            name='imagen_contenido',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='pag2',
            name='imagen_tofi',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
