# Generated by Django 4.0.6 on 2022-08-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bahiaApp', '0010_pag2_imagen_barbi_pag2_imagen_contenido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='formulario',
        ),
    ]
