# Generated by Django 4.0.6 on 2022-08-31 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bahiaApp', '0011_delete_formulario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pag4',
        ),
    ]
