# Generated by Django 4.0.6 on 2022-10-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahiaApp', '0012_delete_pag4'),
    ]

    operations = [
        migrations.AddField(
            model_name='pag3',
            name='descriplong',
            field=models.TextField(default='', max_length=450),
        ),
        migrations.AlterField(
            model_name='pag1',
            name='contenido',
            field=models.TextField(max_length=450),
        ),
        migrations.AlterField(
            model_name='pag1',
            name='testimonio1',
            field=models.TextField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='pag1',
            name='testimonio2',
            field=models.TextField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='pag1',
            name='testimonio3',
            field=models.TextField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='pag1',
            name='titulo',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='pag2',
            name='barbi_1',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pag2',
            name='barbi_3',
            field=models.TextField(default='', max_length=130),
        ),
        migrations.AlterField(
            model_name='pag2',
            name='contenido',
            field=models.TextField(default='', max_length=350),
        ),
        migrations.AlterField(
            model_name='pag2',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pag2',
            name='tofi_1',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pag2',
            name='tofi_3',
            field=models.TextField(default='', max_length=130),
        ),
        migrations.AlterField(
            model_name='pag3',
            name='descripcion',
            field=models.TextField(default='', max_length=110),
        ),
        migrations.AlterField(
            model_name='pag3',
            name='servicio',
            field=models.CharField(default='', max_length=40),
        ),
    ]
