# Generated by Django 4.0.6 on 2022-10-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahiaApp', '0013_pag3_descriplong_alter_pag1_contenido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pag3',
            old_name='descriplong',
            new_name='descripcion_larga',
        ),
        migrations.AlterField(
            model_name='pag3',
            name='servicio',
            field=models.CharField(default='', max_length=60),
        ),
    ]
