# Generated by Django 4.0.6 on 2022-10-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahiaApp', '0014_rename_descriplong_pag3_descripcion_larga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pag1',
            name='testimonio1',
            field=models.TextField(default='', max_length=210),
        ),
        migrations.AlterField(
            model_name='pag1',
            name='testimonio2',
            field=models.TextField(default='', max_length=210),
        ),
        migrations.AlterField(
            model_name='pag1',
            name='testimonio3',
            field=models.TextField(default='', max_length=210),
        ),
    ]
