# Generated by Django 4.0.6 on 2022-10-28 23:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahiaApp', '0015_alter_pag1_testimonio1_alter_pag1_testimonio2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pag1',
            name='clientes_descripcion',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='pag1',
            name='testimonio1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
