# Generated by Django 4.0.6 on 2022-10-29 14:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bahiaApp', '0016_pag1_clientes_descripcion_alter_pag1_testimonio1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pag1',
            name='testimonio2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pag1',
            name='testimonio3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
