# Generated by Django 4.0.6 on 2022-08-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pag4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('telefono', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=50)),
                ('mensaje', models.TextField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Respuestas de formulario',
            },
        ),
    ]
