# Generated by Django 4.0.6 on 2022-08-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pag4',
            name='options',
            field=models.BooleanField(default=False),
        ),
    ]
