# Generated by Django 4.0.6 on 2022-08-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_pag4_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pag4',
            name='options',
            field=models.BooleanField(choices=[('Empresas', 'Empresas'), ('Pyme', 'Pyme'), ('Comercio', 'Comercio'), ('Instiuciones', 'Instituciones')], default=False),
        ),
    ]
