# Generated by Django 4.0.6 on 2022-08-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_alter_pag4_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pag4',
            name='options',
            field=models.CharField(default='', max_length=15),
        ),
    ]
