# Generated by Django 4.0.6 on 2022-10-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_alter_pag4_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pag4',
            name='options',
            field=models.CharField(default='', max_length=50),
        ),
    ]
