# Generated by Django 4.0.6 on 2022-11-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_alter_pag4_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pag4',
            name='nombre',
            field=models.CharField(default='', max_length=60),
        ),
    ]
